<a href="https://colab.research.google.com/github/1boge/my_repos/blob/master/%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8_%D0%BF%D0%BE%D1%82%D0%B5%D1%80%D1%8C_%D0%B8_%D0%BE%D0%BF%D1%82%D0%B8%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from sklearn import datasets
from matplotlib import pyplot as plt
%matplotlib inline
import numpy as np
#from jupyterthemes import jtplot
#jtplot.style()

In [7]:
iris = datasets.load_iris()
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [8]:
#Выбор только двух цветков
X = []
Y = []
for i, unit in enumerate(iris.target):
    if unit != 0:
        X.append(iris.data[i])
        Y.append(unit-1)

X = np.asarray(X)
Y = np.asarray(Y)
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [9]:
def predict(theta, X):
    predict = theta[0] + theta[1] * X[:, 0] + theta[2] * X[:, 1] + theta[3] * X[:, 2] + theta[4] * X[:, 3]
    sigm = 1. / (1 + np.exp(-predict))
    return sigm

In [89]:
#Градиентный спуск
EPOCHS = 100
LEARNING_RATE = 0.05
N = 100
#lr = 0.05
#theta = []
theta = np.random.normal(scale=5, size=N)
#theta = [-0.66556365, -1.46787087, -0.21254648, -0.14877584,  2.22796437]
print(theta)
grad_loss = []
for _ in range(EPOCHS):
    sigm = predict(theta, X)
    theta[0] -= LEARNING_RATE * np.sum(sigm - Y)/len(sigm)
    theta[1] -= LEARNING_RATE * np.sum((sigm - Y) * X[:, 0])/len(sigm)
    theta[2] -= LEARNING_RATE * np.sum((sigm - Y) * X[:, 1])/len(sigm)
    theta[3] -= LEARNING_RATE * np.sum((sigm - Y) * X[:, 2])/len(sigm)
    theta[4] -= LEARNING_RATE * np.sum((sigm - Y) * X[:, 3])/len(sigm)
    loss = - np.mean(np.log(sigm) * Y + np.log(1 - sigm) * (1 - Y))
    print(theta)
    grad_loss.append(loss)

[ 4.84816158e+00 -4.61678526e+00  5.01670842e+00 -2.40636244e-01
 -2.05598270e+00  5.68530763e+00 -3.86374499e-01 -2.60631816e+00
  5.09760973e+00 -1.29374735e+00  2.24451610e+00  4.65980161e+00
  5.63741135e+00  6.37683455e+00 -2.67058892e+00 -2.15145263e+00
  3.48143439e+00  3.34868654e+00 -3.14742061e+00 -7.03871494e+00
 -2.93209605e+00  2.15462820e+00  4.71005801e-01 -4.07553430e-01
 -4.28558528e+00 -4.87970726e+00  5.62220553e-03 -4.70667799e+00
  5.43986979e+00 -6.63354637e-01  9.60687275e+00  2.76023787e+00
  2.42692475e+00  2.74297142e+00  6.19541308e+00 -9.67445568e+00
  3.79510099e-01  1.41599894e+00 -5.72739617e+00  5.02777978e+00
 -3.92974423e+00  5.49154580e+00 -1.58863213e+00  2.68814752e+00
 -4.73002488e+00 -2.80039395e+00 -2.75409231e-01 -4.15009512e-01
  6.13834294e-01 -3.43833122e+00  4.91941055e+00 -1.91590431e+00
 -3.98645189e+00 -3.51710290e-01  7.15730018e+00 -4.34941429e+00
  4.87323467e+00  5.00483343e+00  1.08930924e+00 -8.40158515e+00
  1.18545226e+01  2.95773

In [92]:
error = 0
for i, item in enumerate(np.around(predict(theta, X))):
    if item != Y[i]:
        error += 1
error

52

In [93]:
# Сравниваем результаты классификации
np.matrix([np.around(predict(theta, X)), Y]).T

matrix([[0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [1., 0.],
        [1., 0.],
        [0., 0.],
        [1., 0.],
        [1., 0.],
        [0., 0.],
        [1., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 1.],
        [1., 1.],
        [0., 1.],
        [1., 1.],
        [1., 1.],
        [0

In [14]:
# Надстройка nesterov momentum
EPOCHS = 100
LEARNING_RATE = 0.01
N = 100
#theta = np.random.normal(scale=5, size=N)
theta = [-0.66556365, -1.46787087, -0.21254648, -0.14877584,  2.22796437]
vel_pred = np.zeros(5)
vel = np.zeros(5)
print(theta)
nest_loss = []
gamma = 0.975
for _ in range(EPOCHS):
    sigm = predict(theta, X)
    loss = - np.mean(np.log(sigm) * Y + np.log(1 - sigm) * (1 - Y))
    nest_loss.append(loss)
    sigm = predict(theta - gamma * vel_pred, X)
    vel[0] = (gamma * vel_pred[0] + LEARNING_RATE * np.sum(sigm - Y))/len(sigm)
    vel[1] = (gamma * vel_pred[1] + LEARNING_RATE * np.sum((sigm - Y) * X[:, 0]))/len(sigm)
    vel[2] = (gamma * vel_pred[2] + LEARNING_RATE * np.sum((sigm - Y) * X[:, 1]))/len(sigm)
    vel[3] = (gamma * vel_pred[3] + LEARNING_RATE * np.sum((sigm - Y) * X[:, 2]))/len(sigm)
    vel[4] = (gamma * vel_pred[4] + LEARNING_RATE * np.sum((sigm - Y) * X[:, 3]))/len(sigm)
    theta -= vel
    print(theta)
    vel_pred = vel

[-0.66556365, -1.46787087, -0.21254648, -0.14877584, 2.22796437]
[-0.66057207 -1.43498108 -0.19770042 -0.12105679  2.23807906]
[-0.65554186 -1.40183138 -0.18273855 -0.0931174   2.24827354]
[-0.65052051 -1.36873535 -0.16780231 -0.06522217  2.25845129]
[-0.64551297 -1.33572366 -0.15290619 -0.03739654  2.26860268]
[-0.64052602 -1.30283831 -0.13807013 -0.00967529  2.27871448]
[-0.63556965 -1.27014118 -0.12332348  0.01789026  2.28876716]
[-0.63065826 -1.23772212 -0.10870881  0.04522552  2.29873239]
[-0.62581222 -1.20570866 -0.09428639  0.07222471  2.30857002]
[-0.62105933 -1.17427554 -0.08013863  0.09874294  2.31822526]
[-0.61643566 -1.14365078 -0.06637269  0.12459151  2.32762713]
[-0.61198498 -1.11411233 -0.05311855  0.14954106  2.33669008]
[-0.60775573 -1.08596967 -0.04051999  0.17333737  2.34532048]
[-0.60379559 -1.05952919 -0.0287181   0.19573051  2.35342794]
[-0.60014474 -1.03505105 -0.01783114  0.21651048  2.36093882]
[-0.59683026 -1.01271244 -0.0079379   0.23553708  2.36780672]
[-5.9

In [15]:
error = 0
for i, item in enumerate(np.around(predict(theta, X))):
    if item != Y[i]:
        error += 1
error

9

In [16]:
# Надстройка RMSProp
EPOCHS = 100
LEARNING_RATE = 0.01
N = 100
#theta = np.random.normal(scale=5, size=N)
theta = [-0.66556365, -1.46787087, -0.21254648, -0.14877584,  2.22796437]
e_sq_grad = np.zeros(5)
grad = np.zeros(5)
print(theta)
rmsp_loss = []
gamma = 0.975
eps = 0.00000001
for _ in range(EPOCHS):
    sigm = predict(theta, X)
    loss = - np.mean(np.log(sigm) * Y + np.log(1 - sigm) * (1 - Y))
    rmsp_loss.append(loss)
    grad[0] = np.sum(sigm - Y)/len(sigm)
    grad[1] = np.sum((sigm - Y) * X[:, 0])/len(sigm)
    grad[2] = np.sum((sigm - Y) * X[:, 1])/len(sigm)
    grad[3] = np.sum((sigm - Y) * X[:, 2])/len(sigm)
    grad[4] = np.sum((sigm - Y) * X[:, 3])/len(sigm)
    
    e_sq_grad = gamma * e_sq_grad + (1 - gamma)  * grad ** 2
    
    theta -= LEARNING_RATE * grad / np.sqrt(e_sq_grad + eps)
    print(theta)

[-0.66556365, -1.46787087, -0.21254648, -0.14877584, 2.22796437]
[-0.60231815 -1.40462532 -0.14930093 -0.08553029  2.29120991]
[-0.55738405 -1.35968559 -0.10436482 -0.04058907  2.33614882]
[-0.52057648 -1.3228653  -0.06755338 -0.00376562  2.37296598]
[-0.48867012 -1.29093652 -0.03564126  0.02816851  2.40488738]
[-0.46019998 -1.26243085 -0.00716354  0.05668247  2.43337899]
[-0.43439058 -1.23656878  0.01865499  0.08255693  2.45921769]
[-0.41080369 -1.21290756  0.04225218  0.10623638  2.48284412]
[-0.38918736 -1.19119055  0.06387965  0.12798007  2.50451437]
[-0.36939658 -1.17126817  0.08368241  0.1479412   2.52438019]
[-0.35134427 -1.15304925  0.10174822  0.16621569  2.54253853]
[-0.33496846 -1.1364684   0.11814051  0.1828745   2.55906434]
[-0.3202109  -1.12146471  0.13291975  0.19798458  2.57403109]
[-0.30700511 -1.1079697   0.14615515  0.21162027  2.58752139]
[-0.29527176 -1.09590272  0.15792891  0.22386749  2.59963   ]
[-0.28491921 -1.08517133  0.16833535  0.23482295  2.6104619 ]
[-0.2

In [17]:
error = 0
for i, item in enumerate(np.around(predict(theta, X))):
    if item != Y[i]:
        error += 1
error

11